### ISSUE TITLE
Cant't print

### ISSUE THREAD

**Issue by mrgumorist** [mtmsuhail/ESC-POS-USB-NET#1]
Hi. I have problem with printinting in russian lenguage, i get '?' when i print russian symbols. Can you help me?

**Comment by mtmsuhail** [comment]
could you please share the code that you are running?

**Comment by mrgumorist** [comment]
`using ESC_POS_USB_NET.Printer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp33
{
    class Program
    {
        static void Main(string[] args)
        {
            Printer printer = new Printer("XP-58");
            // printer.BoldMode (ESC_P)
            string foo = "Привет";

            // default encoding
           // byte[] uni = Encoding.ASCII.GetBytes(foo);

            // Convert to ASCII

          //  string Ascii = Encoding.ASCII.GetString(uni);
            printer.Append(foo);
            //printer.Code128("123456789");
            //printer.Separator();
            //printer.Append("Code39");
            //printer.Code39("123456789");
            //printer.Separator();
            //printer.Append("Ean13");
            //printer.Ean13("1234567891231");
            //printer.FullPaperCut();
            printer.PrintDocument();
            printer.Separator();


        }
    }
}
`

**Comment by mrgumorist** [comment]
using ESC_POS_USB_NET.Printer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp33
{
    class Program
    {
        static void Main(string[] args)
        {
            Printer printer = new Printer("XP-58");
            // printer.BoldMode (ESC_P)
            string foo = "Привет";

            // default encoding
           // byte[] uni = Encoding.ASCII.GetBytes(foo);

            // Convert to ASCII

          //  string Ascii = Encoding.ASCII.GetString(uni);
            printer.Append(foo);
            //printer.Code128("123456789");
            //printer.Separator();
            //printer.Append("Code39");
            //printer.Code39("123456789");
            //printer.Separator();
            //printer.Append("Ean13");
            //printer.Ean13("1234567891231");
            //printer.FullPaperCut();
            printer.PrintDocument();
            printer.Separator();


        }
    }
}

**Comment by mrgumorist** [comment]
What can you say about it?

**Comment by mtmsuhail** [comment]
What printer you are using right now?

Is that printer supported russian language?
 
Many languages are not supported by the printers. It depend the manufacturer and the country you are lived in.

We can implement the functionality if the printer internally support it. Please have a look with your manufacturer.

In my case I cannot have an access to russian language printer as I am living in India. But may be I can help you once you confirm it.
