### ISSUE TITLE
Error: 'IBM860' is not a supported encoding name.

### ISSUE THREAD

**Issue by igohang** [mtmsuhail/ESC-POS-USB-NET#10]
Hi!
I just try to print from EPSON TM-T82X Receipt with example code and got this error.
![image](https://user-images.githubusercontent.com/11858449/75551865-ad122400-5a67-11ea-8caa-939d1f4e7239.png)
Thank's :)

**Comment by whc2001** [comment]
At [this position](https://github.com/mtmsuhail/ESC-POS-USB-NET/blob/2de903957145a6f564d9a9eda0612356dd19c6a5/ESC-POS-USB-NET/Printer.cs#L20), try to change the "IBM860" to [other encoding in this list](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netframework-4.8) and try again?

**Comment by jjosez** [comment]
Same issue here.
![image](https://user-images.githubusercontent.com/4119440/76111364-ca824900-5fa5-11ea-81b1-3ddb901d8db5.png)

**Comment by peng0829** [comment]
Hello 
I'm using net core,
 I used "UTF-8" 
It Working

**Comment by mel-ramkhelawan** [comment]
Hi,

How do I go about changing the encode. I'm using dotnet core 3

Thanks

**Comment by eqap-melvinr** [comment]
> Hi,
> 
> How do I go about changing the encode. I'm using dotnet core 3
> 
> Thanks

Managed to solve it.......

**Comment by kvishalv** [comment]
> Hi!
> I just try to print from EPSON TM-T82X Receipt with example code and got this error.
> ![image](https://user-images.githubusercontent.com/11858449/75551865-ad122400-5a67-11ea-8caa-939d1f4e7239.png)
> Thank's :)

I had a similar issue. Below code worked for me
System.Text.EncodingProvider ppp = System.Text.CodePagesEncodingProvider.Instance;
Encoding.RegisterProvider(ppp);

**Comment by mtmsuhail** [comment]
This [issue](https://github.com/mtmsuhail/ESC-POS-USB-NET/commit/44b3ff5f4f482d1c877b08cde3be51a071dfedd0) solved.

Use
`Printer printer = new Printer("Printer Name", "Encoding Name");`
`printer.TestPrinter();`
`printer.FullPaperCut();`
`printer.PrintDocument();`

you can try different types of encoding as shown [here](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netframework-4.8)

**Comment by chami007** [comment]
> > Hi!
> > I just try to print from EPSON TM-T82X Receipt with example code and got this error.
> > ![image](https://user-images.githubusercontent.com/11858449/75551865-ad122400-5a67-11ea-8caa-939d1f4e7239.png)
> > Thank's :)
> 
> I had a similar issue. Below code worked for me
> System.Text.EncodingProvider ppp = System.Text.CodePagesEncodingProvider.Instance;
> Encoding.RegisterProvider(ppp);

Exactly what i was looking for. I  hit above error with my UWP app and your solution did the trick. thanks

**Comment by MarianoGomezBidondo** [comment]
He had the same problem, no matter what codepage he passed as a parameter. What solved it is the answer of chami007. Thank you.

> System.Text.EncodingProvider ppp = System.Text.CodePagesEncodingProvider.Instance;
> Encoding.RegisterProvider(ppp);

**Comment by neo1mmatrix** [comment]
> He had the same problem, no matter what codepage he passed as a parameter. What solved it is the answer of chami007. Thank you.
> 
> > System.Text.EncodingProvider ppp = System.Text.CodePagesEncodingProvider.Instance;
> > Encoding.RegisterProvider(ppp);

Can you tell me where I must write that code please?
