### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by pocitujlasku** [mtmsuhail/ESC-POS-USB-NET#3]
Hi, why is hardcoded encoding to IBM860? im 2 day fixed bad diacritic in printer. 
Please, update code with input for codepage. Its only 3 lines: 
in printer.cs 
**declare private readonly string _codepage;**
and public Printer(string printerName, **string codepage**) {
            **_codepage = codepage;**
}

private void AppendString(string value, bool useLf)
        {
...
            var bytes = Encoding.GetEncoding(**_codepage**).GetBytes(value);
...
        }

Thats all. Thanx for fix.

**Comment by mtmsuhail** [comment]
Updated. Thank you
